Add pa11y comment to PR after it runs

diff --git a/.github/workflows/pa11y.yml b/.github/workflows/pa11y.yml
--- a/.github/workflows/pa11y.yml
+++ b/.github/workflows/pa11y.yml
@@ -58,4 +58,28 @@ jobs:
         env:
           RAILS_ENV: test
           DATABASE_URL: postgres://complaint_tracker:postgres@localhost:5432/complaint_tracker_test
-        run: yarn run pa11y-ci
+        run: yarn run pa11y-ci 2>&1 | tee pa11y_output.txt
+
+      - name: Read pa11y_output file.
+        id: pa11y_output
+        uses: juliangruber/read-file-action@v1
+        with:
+          path: ./pa11y_output.txt
+
+      - name: Comment on pull request.
+        uses: thollander/actions-comment-pull-request@master
+        with:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          message: '
+<details>
+  <summary>Pa11y testing results</summary>
+
+  ```${{ steps.pa11y_output.outputs.content }}```
+
+</details>'
+
+      - name: Check for pa11y failures.
+        if: contains(steps.pa11y_output.outputs.content, 'errno 2')
+        run: |
+          echo "::error::The site is failing accessibility tests. Please review the comment in the pull request or the pa11y-ci step in the workflow for details."
+          exit 1
